/* Generated By:JavaCC: Do not edit this line. Tarea2Constants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Tarea2Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUM = 5;
  /** RegularExpression Id. */
  int CONJUNTO = 6;
  /** RegularExpression Id. */
  int IMPRIME = 7;
  /** RegularExpression Id. */
  int ELIMINA = 8;
  /** RegularExpression Id. */
  int letra = 9;
  /** RegularExpression Id. */
  int ID = 10;
  /** RegularExpression Id. */
  int LLAVE_IZQ = 11;
  /** RegularExpression Id. */
  int LLAVE_DER = 12;
  /** RegularExpression Id. */
  int COMA = 13;
  /** RegularExpression Id. */
  int PUNTO_Y_COMA = 14;
  /** RegularExpression Id. */
  int ASIGNACION = 15;
  /** RegularExpression Id. */
  int OP_MAS = 16;
  /** RegularExpression Id. */
  int OP_MENOS = 17;
  /** RegularExpression Id. */
  int OP_PRODUCTO = 18;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NUM>",
    "\"conjunto\"",
    "\"imprime\"",
    "\"elimina\"",
    "<letra>",
    "<ID>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
  };

}
